# Change these first
owner: sudoswap # Your GitHub organization or username, where this repository lives
repo: status_basecamp_wtf # The name of this repository

sites:
  - name: Main Site
    url: https://basecamp.wtf
  - name: Basecamp API
    url: https://api.basecamp.wtf/stats/platform
    headers:
      - "x-api-key:$API_DEV_TOKEN"
      - "Content-Type: application/json"
  - name: Defined.fi
    method: POST
    url: https://graph.codex.io/graphql
    headers:
      - "Authorization:$DEFINED_API_KEY"
      - "Content-Type: application/json"
    body: '{ "query": "{ getNetworks { name, id } }"}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status_basecamp_wtf
  logoUrl: https://sudoswap.github.io/status_basecamp_wtf/logo.png
  themeUrl: https://sudoswap.github.io/status_basecamp_wtf/theme.css
  name: Basecamp Status
  introTitle: "System Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
